# Generated by Django 2.1 on 2021-06-29 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
